- name: Ensure the ec2 Key Pair exists 
  ec2_key:
    name: "{{ aws_key_pair_name }}"
    profile: "{{ aws_profile_name }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    security_token: "{{ aws_session_token }}"
  register: ec2_key_creation_result
  # FIXME: This play produces an error every time. The response is
  # 'InvalidKeyPair.Dupicate' whatever the key pair name is, even
  # if it's random. I don't know the cause so I'm disabling errors.
  ignore_errors: true
- name: Debug key creation
  debug:
    var: ec2_key_creation_result
    verbosity: 2

- name: The private key is save to a local .pem file
  copy: content="{{ ec2_key_creation_result.key.private_key }}" dest="{{ local_key_pair_path }}" mode=0600
  when: ec2_key_creation_result.changed

- name: Create a symlink to a predictable location
  file:
    state: link
    src: "{{ local_key_pair_path }}"
    dest: "~/.ssh/stroom_aws_key.pem"

- stat:
    path: "{{ local_key_pair_path }}"
  register: key_file_stat

- fail:
    msg: This play ended and no cert is present!
  when: key_file_stat.stat.exists == False
