- name: Check if {{ instance_tag_name }} exists
  ec2_instance_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    security_token: "{{ aws_session_token }}"
    profile: "{{ aws_profile_name }}"
    region: "{{ aws_region }}"
    filters:
      "tag:name": "{{ instance_tag_name }}"
      "tag:environment": "{{ instance_tag_environment }}"
      instance-state-name: [ 
        "shutting-down", 
        "stopping", 
        "stopped", 
        "running", 
        "pending", 
        "rebooting" ]
  register: ec2_instance_query_result

- name: Debug check for {{ instance_tag_name }}
  debug: var=ec2_instance_query_result

- name: Ensure dir for host information is available
  file:
    path: "{{ temp_hosts_dir }}"
    state: directory

- name: Write out the details of this instance to a temporary file
  template:
    src: templates/host_details.j2
    dest: "{{ local_config_dir }}/hosts/{{ instance_tag_name }}"
    
