---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - stack_env_var_file is defined
      - inventory_hostname is defined

- name: "Setting HOST_IP=\"{{ public_ip_address | default(inventory_hostname) }}\" in {{ stack_env_var_file }}"
  lineinfile:
    path: "{{ stack_env_var_file }}"
    regexp: '^\s*#?\s*HOST_IP=.*'
    line: "HOST_IP=\"{{ public_ip_address | default(inventory_hostname) }}\""


