# download_path: "{{ stroom_downloads_path }}"

# Temporary location where the archive files are downloaded to.
# They will not be deleted to save downloding again.
downloads_dir: "/tmp/stroom_downloads"
