# TODO change to a tempdir using tempfile module

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - downloads_dir | default('') | trim != ''
      - stack_install_root_dir | default('') | trim != ''
      - stack_version | default('') | trim != ''
      - stack_name | default('') | trim != ''

- name: Ensure downloads directory exists
  file:
    path: "{{ downloads_dir }}"
    state: directory

- name: Ensure install directory exists
  file:
    path: "{{ stack_install_root_dir }}"
    state: directory

- name: Download stack
  get_url:
    url: "{{ _stroom_stack_archive_url }}"
    dest: "{{ downloads_dir }}/"
    checksum: "sha256:{{ _stroom_stack_archive_url }}.sha256"
  register: download_info

  # FIXME: I can't get the unarchive module to work on macOS or Ubuntu. Ansible complains about /bin/tar not being able
  # to handle the archive. It untars manually without problems, so I'l just do that.
- name: Unpack Stroom's distribution tar
  command: "tar -xvf {{ download_info.dest }} --directory {{ stack_install_root_dir }}"
  args:
    creates: "{{ _stack_bin_dir }}" # Stop the task being re-run if we have downloaded it

#- name: Unpack the stack tar file 
  #unarchive:
    #src: "{{ download_info.dest }}"
    #dest:  "{{ downloads_dir }}"
    #remote_src: yes

#- name: Delete the archive
  #file:
    #path: "{{ download_info.dest }}"
    #state: absent

- name: Create a symlink for 'latest'
  file:
    state: link
    force: yes
    src: "{{ stack_name }}-{{ stack_version }}"
    dest: "{{ stack_install_root_dir }}/{{ stack_name }}/latest"
