- name: Ensure our inventory file has up-to-date public DNS names
  hosts: localhost
  connection: localhost
  gather_facts: false
  vars_files:
    - vars/aws_vault.yml
    - vars/aws.yml
    - ../global_variables.yml
    - ../config/user_settings.yml
  vars:
    temp_hosts_dir: "{{ local_config_dir }}/hosts"
    aws_inventory_file: "{{ local_config_dir }}/aws_inventory.csv"
  tasks:
    - include_role:
        name: roles/ec2/inventory/create
      vars:
        instance_tag_name: stroom_services_stack_1
        instance_tag_type: stroom_services_stack
    - include_role:
        name: roles/ec2/inventory/create
      vars:
        instance_tag_name: stroom_services_stack_2
        instance_tag_type: stroom_services_stack
    - include_role:
        name: roles/ec2/inventory/create
      vars:
        instance_tag_name: stroom_and_proxy_stack_1
        instance_tag_type: stroom_and_proxy_stack
    - include_role:
        name: roles/ec2/inventory/create
      vars:
        instance_tag_name: stroom_and_proxy_stack_2
        instance_tag_type: stroom_and_proxy_stack
    - include_role:
        name: roles/ec2/inventory/create
      vars:
        instance_tag_name: stroom_dbs_stack_1
        instance_tag_type: stroom_dbs_stack
    - name: Concatenate all the inventory files
      shell: cat {{temp_hosts_dir}}/* > {{aws_inventory_file}}
    - name: Remove temp inventory files
      file:
        path: "{{ temp_hosts_dir }}"
        state: absent
    - name: Create ansible format inventory
      command: "python3 ./scripts/create_ansible_inventory.py {{ aws_inventory_file }} {{  ansible_inventory_file }}"
