---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - stack_install_root_dir is defined
      - inventory_hostname is defined

- name: "Setting HOST_IP={{ inventory_hostname }} in {{ _stack_env_file }}"
  replace:
    path: "{{ _stack_env_file }}"
    regexp: '^\s*#?\s*HOST_IP=(?!{{ inventory_hostname }}$).*'
    replace: "HOST_IP={{ inventory_hostname }}"

