---

- name: "Setting {{ item.name }}=\"{{ item.value }}\" in {{ stack_env_var_file }}"
  lineinfile:
    path: "{{ stack_env_var_file }}"
    regexp: '^\s*#?\s*export\s+{{ item.name }}=.*'
    line: "export {{ item.name }}=\"{{ item.value }}\""

