---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - stroom_user is defined

- import_role:
    name: setup/yum_update

# Install EPEL yum repo (for jq install)
- name: Check if EPEL YUM repo is already configured.
  become: true
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result
 
- name: Install EPEL YUM repo.
  become: true
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists
 
- name: Import EPEL GPG key.
  become: true
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists

# Install common command line tools
- name: YUM install various command line tools
  become: true
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - bash
      - coreutils  # realpath is used by some stroom scripts
      - curl
      - htop # Useful process monitoring
      - httpie  # Used by some stroom scripts
      - iproute  # needed for the ip command used in our scripts
      - jq  # Used by some stroom scripts, handy for json munging
      - net-tools
      - python  # Not sure we need it but just in case
      - python3  # Not sure we need it but just in case
      - unzip
      - vim  # vi just doesn't cut it

- name: Ensure firewalld is running
  become: true
  service: 
    name: firewalld 
    state: started 
    enabled: yes

- name: "Ensure we have user {{ stroom_user }} for running stroom software"
  become: true
  user:
    name: "{{ stroom_user }}"
